name: swipe_actions
description: Swipe actions for Flutter
version: 0.0.2
author: Emil Gaarde <gaardee@gmail.com>
homepage: https://github.com/gaardee/flutter_swipe_actions

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
