name: swipe_actions_new
description: Swipe actions for Flutter v3.X.X. Add buttons and callbacks when the child is dragged left or right. Use it and help me improve it.
version: 0.0.2
homepage: https://github.com/aCodeMechanic/swipe_actions_new

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
