name: swipe_actions_new
description: Swipe actions for Flutter v3.X.X
version: 0.0.1
homepage: https://github.com/aCodeMechanic/swipe_actions_new

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
